// Generated by josh-approved-factory/scripts/generate-credits.mjs.
// Source: credits-config.json + package.json + node_modules.
// Do not edit by hand. Re-run the generator after dep updates.

export interface CreditEntry {
  name: string;
  version: string;
  license: string;
  url: string;
}

export const CREDITS_INTRO = "Packing List is built on the work of these open source projects.";

export const CREDITS: CreditEntry[] = [
  {
    "name": "React Native",
    "version": "0.86.0",
    "license": "MIT",
    "url": "https://reactnative.dev/"
  },
  {
    "name": "Expo",
    "version": "57.0.8",
    "license": "MIT",
    "url": "https://github.com/expo/expo/tree/main/packages/expo"
  },
  {
    "name": "React Navigation",
    "version": "7.2.4",
    "license": "MIT",
    "url": "https://reactnavigation.org"
  },
  {
    "name": "Zustand",
    "version": "5.0.13",
    "license": "MIT",
    "url": "https://github.com/pmndrs/zustand"
  },
  {
    "name": "Reanimated",
    "version": "4.5.0",
    "license": "MIT",
    "url": "https://docs.swmansion.com/react-native-reanimated"
  },
  {
    "name": "Gesture Handler",
    "version": "2.32.0",
    "license": "MIT",
    "url": "https://docs.swmansion.com/react-native-gesture-handler/"
  },
  {
    "name": "Reorderable List",
    "version": "0.18.0",
    "license": "MIT",
    "url": "https://github.com/omahili/react-native-reorderable-list#readme"
  },
  {
    "name": "Expo SQLite",
    "version": "57.0.1",
    "license": "MIT",
    "url": "https://docs.expo.dev/versions/latest/sdk/sqlite/"
  },
  {
    "name": "react-native-svg",
    "version": "15.15.4",
    "license": "MIT",
    "url": "https://github.com/react-native-community/react-native-svg"
  },
  {
    "name": "Lucide",
    "version": "1.16.0",
    "license": "ISC",
    "url": "https://lucide.dev"
  },
  {
    "name": "IBM Plex",
    "version": "",
    "license": "OFL 1.1",
    "url": "https://www.ibm.com/plex/"
  }
];
